# Generated by Django 3.2.9 on 2021-11-18 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('reg_no', models.CharField(max_length=4, verbose_name='Reg no')),
                ('level', models.CharField(blank=True, choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SSS1', 'SSS1'), ('SSS2', 'SSS2'), ('SSS3', 'SSS3')], max_length=4, null=True, verbose_name='Student level/class')),
                ('department', models.CharField(blank=True, choices=[('Art', 'Art'), ('Science', 'Science'), ('Commercial', 'Commercial'), ('Social Science', 'Social Science')], max_length=255, null=True, verbose_name='Department')),
                ('parent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Parent/Guardian')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('staff_id', models.CharField(help_text='Example: <b>STF1234</b>', max_length=7, unique=True, verbose_name='Staff ID')),
                ('level', models.CharField(blank=True, max_length=255, null=True, verbose_name='Level')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('reg_no', 'level', 'department'), name='unique student'),
        ),
    ]
