# Generated by Django 3.2.9 on 2021-11-27 13:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('detail', models.TextField(verbose_name='Details')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created')),
                ('by', models.ForeignKey(help_text='The staff who made the comments.', on_delete=django.db.models.deletion.CASCADE, to='careerguide.staff')),
                ('student', models.ForeignKey(help_text='The student the comment is made for.', on_delete=django.db.models.deletion.CASCADE, to='careerguide.student')),
            ],
        ),
    ]
