# Generated by Django 3.2.9 on 2021-12-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
