# Generated by Django 3.2.9 on 2021-12-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0002_alter_questionnaire_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SID'),
        ),
    ]
