# Generated by Django 3.2.9 on 2021-11-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0002_auto_20211118_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Art', 'Art'), ('Science', 'Science'), ('Commercial', 'Commercial'), ('Social Science', 'Social Science')], max_length=255, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SSS1', 'SSS1'), ('SSS2', 'SSS2'), ('SSS3', 'SSS3')], max_length=4, null=True, verbose_name='Student level/class'),
        ),
    ]
