# Generated by Django 3.2.9 on 2021-11-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0003_rename_by_comment_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
