# Generated by Django 3.2.9 on 2021-11-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0003_auto_20211119_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Art', 'Art'), ('Science', 'Science'), ('Commercial', 'Commercial'), ('Social Science', 'Social Science')], default='', max_length=255, verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SSS1', 'SSS1'), ('SSS2', 'SSS2'), ('SSS3', 'SSS3')], default='', max_length=4, verbose_name='Student level/class'),
            preserve_default=False,
        ),
    ]
