# Generated by Django 3.2.9 on 2021-12-31 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0003_student_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='before',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Before'),
        ),
    ]
