# Generated by Django 3.2.9 on 2021-12-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0004_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='other_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Other Name'),
            preserve_default=False,
        ),
    ]
