# Generated by Django 3.2.9 on 2021-11-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0004_auto_20211119_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('art', 'art'), ('science', 'science'), ('commercial', 'commercial'), ('social science', 'Social Science')], max_length=255, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('jss1', 'jss1'), ('jss2', 'jss2'), ('jss3', 'JSS3'), ('sss1', 'sss1'), ('sss2', 'sss2'), ('sss3', 'SSS3')], max_length=4, verbose_name='Student level/class'),
        ),
    ]
