# Generated by Django 3.2.9 on 2021-12-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0005_alter_profile_other_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Observation',
        ),
    ]
