# Generated by Django 3.2.9 on 2021-11-21 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0006_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, null=True, verbose_name='Title slug')),
                ('question', models.TextField(verbose_name='Question')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerguide.staff')),
                ('student', models.ManyToManyField(related_name='students', to='careerguide.Student')),
            ],
        ),
    ]
