# Generated by Django 3.2.9 on 2021-11-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0007_auto_20211121_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
