# Generated by Django 3.2.9 on 2021-11-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0008_questionnaire_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='student',
            new_name='students',
        ),
    ]
