# Generated by Django 3.2.9 on 2022-01-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0008_alter_schedule_before'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='before',
            new_name='expire',
        ),
    ]
