# Generated by Django 3.2.9 on 2021-11-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0009_rename_student_questionnaire_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='students',
            field=models.ManyToManyField(related_name='questions', to='careerguide.Student'),
        ),
    ]
