# Generated by Django 3.2.9 on 2021-12-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0009_alter_questionnaire_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='categories',
            field=models.CharField(help_text='Comma/space seperated values representing the type of students this questionnaire is ment for<br>E.G: art, ss1, male', max_length=255, verbose_name='Categories'),
        ),
    ]
