# Generated by Django 3.2.9 on 2021-12-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0010_alter_questionnaire_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='categories',
            field=models.CharField(blank=True, help_text='Comma/space seperated values representing the type of students this questionnaire is ment for<br>E.G: art, ss1, male', max_length=255, verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('art', 'art'), ('science', 'science'), ('commercial', 'commercial'), ('social science', 'social science')], max_length=255, verbose_name='Department'),
        ),
    ]
