# Generated by Django 3.2.9 on 2021-11-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0011_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
