# Generated by Django 3.2.9 on 2022-03-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0011_result_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, null=True, verbose_name='Title slug')),
                ('question', models.TextField(verbose_name='Question')),
            ],
        ),
    ]
