# Generated by Django 3.2.9 on 2022-03-16 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0012_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created'),
        ),
    ]
