# Generated by Django 3.2.9 on 2021-11-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0012_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('jss1', 'jss1'), ('jss2', 'jss2'), ('jss3', 'JSS3'), ('sss1', 'sss1'), ('sss2', 'sss2'), ('sss3', 'SSS3')], max_length=4, verbose_name='Student level'),
        ),
    ]
