# Generated by Django 3.2.9 on 2021-11-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0014_auto_20211123_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.CharField(blank=True, max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(blank=True, max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
